[build]
builder = "DOCKERFILE"
dockerfilePath = "./Dockerfile"
watchPatterns = [
    "requirements.txt", 
    "src/**", 
    "railway.toml",
    "Dockerfile",
]
[start]
command = "gunicorn cfehome.wsgi:application --bind 0.0.0.0:$PORT"
