# Generated by Django 5.0.9 on 2024-11-25 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0011_subscriptionprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionprice',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscriptions.subscription'),
        ),
    ]
